### PR TITLE
Windows port, some tests added, documentation as well.

### PR DESCRIPTION
**Pull request by keltia**
First I wanted to add some tests then as I wanted to test it on my Windows machine, I did the port.

Enjoy! :)

### CODE REVIEW

**Comment by keltia** [comment]
Sorry I messed up the commits a bit while doing `git commit -p`.

**Comment by fanf2** [comment]
This is wonderful, thanks!

Can you please make a couple of changes? then it should be good to merge:

  * Please squash the first two commits, "some documentation..." and "port datez to windows". Most of the interesting portability code is in the "documentation" commit, but the history will be more clear if it is in the "port" commit.

  * Please drop the README.md "Reformat" patch - I have _opinions_ about my markdown :-)

Thanks again!

**Comment by keltia** [comment]
According to Tony Finch on Tue, Nov 09, 2021 at 03:26:29AM -0800:
> Can you please make a couple of changes? then it should be good to merge:
> 
>   * Please squash the first two commits, "some documentation..." and "port datez to windows". Most of the interesting portability code is in the "documentation" commit, but the history will be more clear if it is in the "port" commit.

I can do but do I have to remove the pull request and start one again?  I have never done that before :)

>   * Please drop the README.md "Reformat" patch - I have _opinions_ about my markdown :-)

Ok :)

-- 
Ollivier ROBERT -=- FreeBSD: The Power to Serve! -=- ***@***.***
In memoriam to Ondine, our 2nd child: http://ondine.keltia.net/

**Comment by fanf2** [comment]
To update the pull request, you can `git rebase -i` to change the local copy of your `add-stuff` branch, then `git push --force` to update the copy on GitHub, which should automatically update the pull request. I think :-)

**Comment by keltia** [comment]
Ok, tell me how it looks now.

**Comment by fanf2** [comment]
Superfine :-)

**Comment by keltia** [comment]
According to Tony Finch on Tue, Nov 09, 2021 at 06:16:54AM -0800:
> Merged #1 into trunk.

Thanks!
-- 
Ollivier ROBERT -=- FreeBSD: The Power to Serve! -=- ***@***.***
In memoriam to Ondine, our 2nd child: http://ondine.keltia.net/

**Pull request merged**
